# server setting
server:
    port: 8080
# spring setting
spring:
    application:
        name: sushi-shop
    profiles:
        active: dev
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
        username: sa
        password:
    sql:
        init:
            platform: h2
            schema-locations: classpath:./sql/schema.sql
            data-locations: classpath:./sql/data.sql
    jpa:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          ddl-auto: update
    data:
        redis:
            host: localhost
            port: 6379
            database: 0
    jackson:
        serialization:
          indent-output: true